//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceFingerNation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alimentos
    {
        public int id { get; set; }
        public string categoria { get; set; }
        public string nombre { get; set; }
        public Nullable<double> calorias { get; set; }
        public string marca { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string unidadmedida { get; set; }
        public Nullable<double> carbohidratos { get; set; }
        public Nullable<double> fibra { get; set; }
        public Nullable<double> azucar { get; set; }
        public Nullable<double> proteinas { get; set; }
        public Nullable<double> grasas { get; set; }
        public Nullable<double> monoinsaturadas { get; set; }
        public Nullable<double> poliinsaturadas { get; set; }
        public Nullable<double> saturadas { get; set; }
        public Nullable<double> sodio { get; set; }
    }
}
